/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaTaskBusiness 
{
	partial interface IImardaTask 
	{

		#region Operation Contracts for ScheduledTask
		[OperationContract]
		GetListResponse<ScheduledTask> GetScheduledTaskListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<ScheduledTask> GetScheduledTaskList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveScheduledTaskList(SaveListRequest<ScheduledTask> request);

		[OperationContract]
		BusinessMessageResponse SaveScheduledTask(SaveRequest<ScheduledTask> request);

		[OperationContract]
		BusinessMessageResponse DeleteScheduledTask(IDRequest request);

		[OperationContract]
		GetItemResponse<ScheduledTask> GetScheduledTask(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetScheduledTaskUpdateCount(GetUpdateCountRequest request);

		[OperationContract]
		BusinessMessageResponse UpdateScheduledTaskOwnerID(SaveRequest<ScheduledTask> request);
		#endregion

	}
}


