/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 2:48 p.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernServiceBase;

namespace ImardaReportService {
	public class ProjectInstaller : BaseProjectInstaller {
		public ProjectInstaller()
			: base("ImardaReport", "ImardaReportService",
			"Provides a System.ServiceModel Service Contract to get information from, and save information to, the ImardaReport Database.") { }
	}
}


