/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 2:48 p.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using ImardaReportBusiness;
using System.Data.SqlClient;
using Imarda.Lib;

namespace ImardaReport 
{

	public class ImardaReportService : FernServiceBase.FernBusinessServiceBase 
	{

		/// <summary>
		/// Passes the specific args for this Service to the base class
		/// </summary>
		public ImardaReportService()
			: base("ImardaReport")
		{
			RegisterHost(new ImardaServiceHost(typeof(ImardaReportBusiness.ImardaReport)));
		}

		/// <summary>
		/// Main program entry point
		/// </summary>
		public static void Main() 
		{
			System.ServiceProcess.ServiceBase[] ServicesToRun;
			ServicesToRun = new System.ServiceProcess.ServiceBase[] { new ImardaReportService() };
			System.ServiceProcess.ServiceBase.Run(ServicesToRun);
		}

		#region Methods to re-initialize, or update, the database.
		protected override void InternalUpdateDatabase(SqlConnection conn) 
		{
			
		}
		#endregion
	}
}

