/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/03/2010 12:10 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;


namespace ImardaCRMBusiness
{
	partial class ImardaCRM
	{
		public GetItemResponse<NotificationHistory> GetNotificationHistory(IDRequest request)
		{
			try
			{
				return GenericGetEntity<NotificationHistory>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<NotificationHistory>>(ex);
			}
		}

		public GetUpdateCountResponse GetNotificationHistoryUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<NotificationHistory>("NotificationHistory", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<NotificationHistory> GetNotificationHistoryListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<NotificationHistory>("NotificationHistory", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<NotificationHistory>>(ex);
			}
		}

		public GetListResponse<NotificationHistory> GetNotificationHistoryList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<NotificationHistory>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<NotificationHistory>>(ex);
			}
		}
		
		public BusinessMessageResponse SaveNotificationHistory(SaveRequest<NotificationHistory> request)
		{
			try
			{
				NotificationHistory entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				 			   
				object [] properties=new object[]
				{
						entity.ID,
						entity.CRMID,
						entity.NotificationPlanID,
						entity.DeliveryMethod,
						entity.Content,
						entity.Status,
						entity.CompanyID,
						entity.UserID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                var response = GenericSaveEntity<NotificationHistory>(entity.CompanyID, entity.Attributes, properties);  //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveNotificationHistoryList(SaveListRequest<NotificationHistory> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (NotificationHistory entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object [] properties=new object[]
					{
						entity.ID,
						entity.CRMID,
						entity.NotificationPlanID,
						entity.DeliveryMethod,
						entity.Content,
						entity.Status,
						entity.CompanyID,
						entity.UserID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                    response = GenericSaveEntity<NotificationHistory>(entity.CompanyID, entity.Attributes, properties); 				     //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteNotificationHistory(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<NotificationHistory>("NotificationHistory", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}


