/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\qian.chen
Date Generated : 07/02/2011 11:32 a.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaSecurityBusiness
{
    partial interface IImardaSecurity
    {

        #region Operation Contracts for LogonLog
        [OperationContract]
        GetListResponse<LogonLog> GetLogonLogListByTimeStamp(GetListByTimestampRequest request);

        [OperationContract]
        GetListResponse<LogonLog> GetLogonLogList(IDRequest request);

        [OperationContract]
        BusinessMessageResponse SaveLogonLogList(SaveListRequest<LogonLog> request);

        [OperationContract]
        BusinessMessageResponse SaveLogonLog(SaveRequest<LogonLog> request);

        [OperationContract]
        BusinessMessageResponse DeleteLogonLog(IDRequest request);

        [OperationContract]
        GetItemResponse<LogonLog> GetLogonLog(IDRequest request);

        [OperationContract]
        GetUpdateCountResponse GetLogonLogUpdateCount(GetUpdateCountRequest request);
        #endregion

    }
}


