/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for SMSDraft
		[OperationContract]
		GetListResponse<SMSDraft> GetSMSDraftListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<SMSDraft> GetSMSDraftList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveSMSDraftList(SaveListRequest<SMSDraft> request);

		[OperationContract]
		BusinessMessageResponse SaveSMSDraft(SaveRequest<SMSDraft> request);

		[OperationContract]
		BusinessMessageResponse DeleteSMSDraft(IDRequest request);

		[OperationContract]
		GetItemResponse<SMSDraft> GetSMSDraft(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetSMSDraftUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


