/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.Serialization;
using FernBusinessBase;
using System.Data;
using FernBusinessBase.Control;

namespace ImardaTaskBusiness 
{
	[DataContract]
	public class Task : FullBusinessEntity 
	{				
		#region Constructor
		public Task():base()
		{
		}
		#endregion
		
		#region Properties
		[DataMember]
		public Guid ParentID 
		{get ;set ;}
		[DataMember]
		public Int16 Ord 
		{get ;set ;}
		[DataMember]
		public bool IsTemplate 
		{get ;set ;}
		public const int PreconditionMaxLen = 120;
		[ValidLength(-1, PreconditionMaxLen)]
		[DataMember]
		public string Precondition 
		{get ;set ;}
		public const int ProgramMaxLen = 120;
		[ValidLength(-1, ProgramMaxLen)]
		[DataMember]
		public string Program 
		{get ;set ;}
		public const int WorkerMaxLen = 50;
		[ValidLength(-1, WorkerMaxLen)]
		[DataMember]
		public string Worker 
		{get ;set ;}
		[DataMember]
		public int Status 
		{get ;set ;}
		[DataMember]
		public int EstimatedDuration 
		{get ;set ;}
		[DataMember]
		public DateTime EndTime 
		{get ;set ;}
#if EntityProperty
		[DataMember]
		public `cstype` `field` { get; set; }
#endif
		
		#endregion

		#region Methods
		public override void AssignData(IDataReader dr) 
		{
			base.AssignData(dr);
			ParentID = GetValue<Guid>(dr, "ParentID");
			Ord = GetValue<Int16>(dr, "Ord");
			IsTemplate = GetValue<bool>(dr, "IsTemplate");
			Precondition = GetValue<string>(dr, "Precondition");
			Program = GetValue<string>(dr, "Program");
			Worker = GetValue<string>(dr, "Worker");
			Status = GetValue<int>(dr, "Status");
			EstimatedDuration = GetValue<int>(dr, "EstimatedDuration");
			EndTime = GetDateTime(dr, "EndTime");
#if EntityProperty_NoDate
			`field` = GetValue<`cstype`>(dr, "`field`");
#endif
#if EntityProperty_Date
			`field` = GetDateTime(dr, "`field`");
#endif
		
		}

		#endregion

	
	}
}

