/***********************************************************************
Auto Generated Code.

Generated by   : INZ09PC016\maurice.verheijen
Date Generated : 10-2-11 11:52 a.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaCRMBusiness 
{
	partial interface IImardaCRM 
	{

		#region Operation Contracts for NotificationPlanItem
		[OperationContract]
		GetListResponse<NotificationPlanItem> GetNotificationPlanItemListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<NotificationPlanItem> GetNotificationPlanItemList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveNotificationPlanItemList(SaveListRequest<NotificationPlanItem> request);

		[OperationContract]
		BusinessMessageResponse SaveNotificationPlanItem(SaveRequest<NotificationPlanItem> request);

		[OperationContract]
		BusinessMessageResponse DeleteNotificationPlanItem(IDRequest request);

		[OperationContract]
		GetItemResponse<NotificationPlanItem> GetNotificationPlanItem(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetNotificationPlanItemUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


