/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaCRMBusiness 
{
	partial interface IImardaCRM 
	{

		#region Operation Contracts for Company
		[OperationContract]
		GetListResponse<Company> GetCompanyListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<Company> GetCompanyList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveCompanyList(SaveListRequest<Company> request);

		[OperationContract]
		BusinessMessageResponse SaveCompany(SaveRequest<Company> request);

		[OperationContract]
		GetItemResponse<Company> GetCompany(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetCompanyUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


