/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for EmailDraft
		[OperationContract]
		GetListResponse<EmailDraft> GetEmailDraftListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<EmailDraft> GetEmailDraftList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveEmailDraftList(SaveListRequest<EmailDraft> request);

		[OperationContract]
		BusinessMessageResponse SaveEmailDraft(SaveRequest<EmailDraft> request);

		[OperationContract]
		BusinessMessageResponse DeleteEmailDraft(IDRequest request);

		[OperationContract]
		GetItemResponse<EmailDraft> GetEmailDraft(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetEmailDraftUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


