/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 2:48 p.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.ServiceModel;
using System.Xml;
using System.ServiceModel.Channels;
//using System.Web.Services.Description;
using ImardaReportBusiness ;
using FernBusinessBase;

public public class ImardaProxyManager
{
	#region ImardaReportService
	private Proxy<IImardaReport> _IImardaReportProxy
			= new Proxy<IImardaReport>("ReportingTcpEndpoint");
		public IImardaReport IImardaReportProxy
		{
			get { return _IImardaReportProxy.GetChannel(); }
		}

	#endregion
}



