/***********************************************************************
Auto Generated Code

Generated by   : adam-Laptop\adam
Date Generated : 28/04/2009 12:24 PM
Copyright @2009 CodeGenerator
***********************************************************************/
#region

using FernBusinessBase;
//using ImardaConfigurationBusiness;
//using ImardaCRMBusiness;
using ImardaSecurityBusiness;

//using ImardaUKITCameraInjectorInterface;


#endregion

namespace Imarda360Application
{
	public class ImardaProxyManager
	{
		#region ImardaProxyManager is a Singleton

		public static ImardaProxyManager Instance
		{
			get
			{
				if (_Instance == null) _Instance = new ImardaProxyManager();
				return _Instance;
			}
		}

		private static ImardaProxyManager _Instance;

		/// <summary>
		/// Constructs the one and only ImardaProxyManager.
		/// </summary>
		private ImardaProxyManager()
		{

		}

		#endregion
		#region ImardaTrackingService
        private Proxy<Cormit.Business.RouteTracking.ICormitRouteTracking> _IImardaTrackingProxy = new Proxy<Cormit.Business.RouteTracking.ICormitRouteTracking>("TrackingTcpEndpoint");
        public Cormit.Business.RouteTracking.ICormitRouteTracking IImardaTrackingProxy
		{
			get { return _IImardaTrackingProxy.GetChannel(); }
		}

        public Proxy<Cormit.Business.RouteTracking.ICormitRouteTracking> ImardaTrackingProxy
        {
            get { return _IImardaTrackingProxy; }
        }

        public Proxy<Cormit.Business.RouteTracking.ICormitRouteTracking> IImardaTracking
		{
			get { return _IImardaTrackingProxy; }
		}

		#endregion
		
    }
}


