/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 2:48 p.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;
using Imarda.Lib;
using Imarda.Logging;

namespace ImardaReportBusiness
{
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.Single, ConcurrencyMode = ConcurrencyMode.Multiple)]
	public partial class ImardaReport : FernBusinessBase.BusinessBase, IImardaReport
	{
		public static readonly Guid InstanceID = SequentialGuid.NewDbGuid();
		public const string Description = "Report Infrastructure";

		public ErrorLogger _Log = ErrorLogger.GetLogger("Reporting");
	}
}

