/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/03/2010 12:10 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaCRMBusiness 
{
	partial interface IImardaCRM 
	{

		#region Operation Contracts for NotificationItem
		[OperationContract]
		GetListResponse<NotificationItem> GetNotificationItemListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<NotificationItem> GetNotificationItemList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveNotificationItemList(SaveListRequest<NotificationItem> request);

		[OperationContract]
		BusinessMessageResponse SaveNotificationItem(SaveRequest<NotificationItem> request);

		[OperationContract]
		BusinessMessageResponse DeleteNotificationItem(IDRequest request);

		[OperationContract]
		GetItemResponse<NotificationItem> GetNotificationItem(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetNotificationItemUpdateCount(GetUpdateCountRequest request);

		#endregion

	}
}


