/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;
namespace ImardaCRMBusiness
{
	partial class ImardaCRM
	{

		#region Get EmailGroup
		public GetItemResponse<EmailGroup> GetEmailGroup(IDRequest request)
		{
			try
			{
				return GenericGetEntity<EmailGroup>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<EmailGroup>>(ex);
			}
		}
		#endregion
		#region GetEmailGroupUpdateCount
		

		public GetUpdateCountResponse GetEmailGroupUpdateCount(GetUpdateCountRequest request)
		{
			GetUpdateCountResponse response = new GetUpdateCountResponse();

			try
			{
				response = GenericGetEntityUpdateCount<EmailGroup>("EmailGroup", request.TimeStamp, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}

			return response;
		}
		#endregion
		#region GetEmailGroupListByTimeStamp
		

		public GetListResponse<EmailGroup> GetEmailGroupListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<EmailGroup>("EmailGroup", request.TimeStamp, request.Cap, true, request.IncludeInactive, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<EmailGroup>>(ex);
			}
		}
		#endregion
		#region GetEmailGroupList
		

		public GetListResponse<EmailGroup> GetEmailGroupList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<EmailGroup>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<EmailGroup>>(ex);
			}
		}
		#endregion
		#region Save EmailGroup
		public BusinessMessageResponse SaveEmailGroup(SaveRequest<EmailGroup> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				EmailGroup entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				 			   
				object [] properties=new object[]{			entity.ID,
						entity.Active,
						entity.Deleted,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.CompanyID,
						entity.UserID,
						entity.GroupName,
						entity.GroupDescription,
						entity.GroupEmailRecipients,
						entity.GroupEmailAddresses
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                response = GenericSaveEntity<EmailGroup>(entity.CompanyID, entity.Attributes, properties);    //Review IM-3747
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region SaveEmailGroupList
		

		public BusinessMessageResponse SaveEmailGroupList(SaveListRequest<EmailGroup> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (EmailGroup entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object [] properties=new object[]
					{
						entity.ID,
						entity.Active,
						entity.Deleted,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.CompanyID,
						entity.UserID,
						entity.GroupName,
						entity.GroupDescription,
						entity.GroupEmailRecipients,
						entity.GroupEmailAddresses
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                    response = GenericSaveEntity<EmailGroup>(entity.CompanyID, entity.Attributes, properties); 				       //Review IM-3747
				}
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region Delete EmailGroup
		

		public BusinessMessageResponse DeleteEmailGroup(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<EmailGroup>("EmailGroup", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
		#endregion
	}
}


