/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for SMSPending
		[OperationContract]
		GetListResponse<SMSPending> GetSMSPendingListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<SMSPending> GetSMSPendingList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveSMSPendingList(SaveListRequest<SMSPending> request);

		[OperationContract]
		BusinessMessageResponse SaveSMSPending(SaveRequest<SMSPending> request);

		[OperationContract]
		BusinessMessageResponse DeleteSMSPending(IDRequest request);

		[OperationContract]
		GetItemResponse<SMSPending> GetSMSPending(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetSMSPendingUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


