/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for SMSFailed
		[OperationContract]
		GetListResponse<SMSFailed> GetSMSFailedListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<SMSFailed> GetSMSFailedList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveSMSFailedList(SaveListRequest<SMSFailed> request);

		[OperationContract]
		BusinessMessageResponse SaveSMSFailed(SaveRequest<SMSFailed> request);

		[OperationContract]
		BusinessMessageResponse DeleteSMSFailed(IDRequest request);

		[OperationContract]
		GetItemResponse<SMSFailed> GetSMSFailed(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetSMSFailedUpdateCount(GetUpdateCountRequest request);

		[OperationContract]
		GetListResponse<SMSFailed> GetSMSFailedDueList(IDRequest request);
		#endregion

	}
}


