/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for SMSSent
		[OperationContract]
		GetListResponse<SMSSent> GetSMSSentListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<SMSSent> GetSMSSentList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveSMSSentList(SaveListRequest<SMSSent> request);

		[OperationContract]
		BusinessMessageResponse SaveSMSSent(SaveRequest<SMSSent> request);

		[OperationContract]
		BusinessMessageResponse DeleteSMSSent(IDRequest request);

		[OperationContract]
		GetItemResponse<SMSSent> GetSMSSent(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetSMSSentUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


