/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaTaskBusiness 
{
	/// <summary>
	/// Type of Task.Status
	/// </summary>
	public enum TaskStatus : byte
	{
		New = 0, // task has just been put into the database ScheduleTask table
		Queued = 1, // task has been read from database and submitted to task queue cache
		QueueError = 2, // error while queueing
		Success = 3, // processed with success
		Failure = 4, // failure trying to process
		Incomplete = 5, // the work may be incomplete and should be patched later
		Retries = 6, // too many retries, all failed
		Exception = 7, // some exception in the job's work routine happened
		TimedOut = 8, // took too long
		Cancelled = 9, // removed by client.
		Rescheduled = 10, // the task had Active=0 and was only there as template and to calculate a proper start time
		Unknown = 99
	}

	[ServiceContract]
	public partial interface IImardaTask : IServerFacadeBase
	{
	}
}

