/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernServiceBase;

namespace ImardaTaskService {
	public class ProjectInstaller : BaseProjectInstaller {
		public ProjectInstaller()
			: base("ImardaTask", "ImardaTaskService",
			"Provides a System.ServiceModel Service Contract to get information from, and save information to, the ImardaTask Database.") 
			{ }
	}
}


