/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using ImardaTaskBusiness;
using System.Data.SqlClient;
using Imarda.Lib;

namespace ImardaTask 
{

	public class ImardaTaskService : FernServiceBase.FernBusinessServiceBase 
	{

		/// <summary>
		/// Passes the specific args for this Service to the base class
		/// </summary>
		public ImardaTaskService()
			: base("ImardaTask")
		{
			RegisterHost(new ImardaServiceHost(typeof(ImardaTaskBusiness.ImardaTask)));
		}

		/// <summary>
		/// Main program entry point
		/// </summary>
		public static void Main() 
		{
			System.ServiceProcess.ServiceBase[] ServicesToRun;
			ServicesToRun = new System.ServiceProcess.ServiceBase[] { new ImardaTaskService() };
			System.ServiceProcess.ServiceBase.Run(ServicesToRun);
		}

		#region Methods to re-initialize, or update, the database.
		protected override void InternalUpdateDatabase(SqlConnection conn) 
		{
			
		}
		#endregion
	}
}

