/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 12/05/2009 12:13 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Data;
using System.Runtime.Serialization;
using FernBusinessBase;
using FernBusinessBase.Control;

namespace ImardaConfigurationBusiness 
{
	[DataContract]
	public class Configuration : FullBusinessEntity 
	{				
	
		#region Properties

		[DataMember]
		public bool Combine 
		{get ;set ;}
		[DataMember]
		public Byte ValueType 
		{get ;set ;}
		[DataMember]
		public string VersionValue 
		{get ;set ;}
		public const int NotesMaxLen = 100;
		[ValidLength(-1, NotesMaxLen)]
		[DataMember]
		public string Notes 
		{get ;set ;}
		[DataMember]
		public Byte Hierarchy 
		{get ;set ;}
		[DataMember]
		public Guid Level1 
		{get ;set ;}
		[DataMember]
		public Guid Level2 
		{get ;set ;}
		[DataMember]
		public Guid Level3 
		{get ;set ;}
		[DataMember]
		public Guid Level4 
		{get ;set ;}
		[DataMember]
		public Guid Level5 
		{get ;set ;}

		[DataMember]
		public Guid UID
		{ get; set; }
#if EntityProperty
		[DataMember]
		public `cstype` `field` { get; set; }
#endif
		


		#endregion

		#region Methods
		public override void AssignData(IDataReader dr) 
		{
			base.AssignData(dr);
			Combine = GetValue<bool>(dr, "Combine");
			ValueType = GetValue<Byte>(dr, "ValueType");
			VersionValue = GetValue<string>(dr, "VersionValue");
			Notes = GetValue<string>(dr, "Notes");
			Hierarchy = GetValue<Byte>(dr, "Hierarchy");
			Level1 = GetValue<Guid>(dr, "Level1");
			Level2 = GetValue<Guid>(dr, "Level2");
			Level3 = GetValue<Guid>(dr, "Level3");
			Level4 = GetValue<Guid>(dr, "Level4");
			Level5 = GetValue<Guid>(dr, "Level5");
			UID = GetValue<Guid>(dr, "UID");
#if EntityProperty_NoDate
			`field` = GetValue<`cstype`>(dr, "`field`");
#endif
#if EntityProperty_Date
			`field` = GetDateTime(dr, "`field`");
#endif
		
		}

		#endregion

	
	}
}

