/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using ImardaCRMBusiness;

namespace TestBusinessHost.Services
{
	public class ImardaCRMBusinessHost :ServiceHostBase
	{
		protected override Type ServiceType
		{
			get { return typeof(ImardaCRMBusiness.ImardaCRM ); }
		}

		protected override string ServiceName
		{
			get { return "Imarda CRM Business Host"; }
		}
	}
}


