/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 12:59 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernServiceBase;

namespace ImardaLoggingService
{
	public class ProjectInstaller : BaseProjectInstaller {
		public ProjectInstaller()
            : base("ImardaLogging", "ImardaLoggingService",
            "Provides Logging Related Information") { }
	}
}


