/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for EmailSent
		[OperationContract]
		GetListResponse<EmailSent> GetEmailSentListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<EmailSent> GetEmailSentList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveEmailSentList(SaveListRequest<EmailSent> request);

		[OperationContract]
		BusinessMessageResponse SaveEmailSent(SaveRequest<EmailSent> request);

		[OperationContract]
		BusinessMessageResponse DeleteEmailSent(IDRequest request);

		[OperationContract]
		GetItemResponse<EmailSent> GetEmailSent(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetEmailSentUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


