/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 12/05/2009 12:13 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;
using Imarda.Lib;
using Imarda360.Infrastructure.ConfigurationService;

namespace ImardaConfigurationBusiness
{
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.Single, ConcurrencyMode = ConcurrencyMode.Multiple)]
	public partial class ImardaConfiguration : FernBusinessBase.BusinessBase, IImardaConfiguration, IConfigData
	{
		public static readonly Guid InstanceID = SequentialGuid.NewDbGuid();
		public const string Description = "I360 Configuration Application";

	}
}

