/***********************************************************************
Auto Generated Code.

Generated by   : INZ09PC016\maurice.verheijen
Date Generated : 10-2-11 11:52 a.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;


namespace ImardaCRMBusiness
{
	partial class ImardaCRM
	{
		public GetItemResponse<NotificationPlanItem> GetNotificationPlanItem(IDRequest request)
		{
			try
			{
				return GenericGetEntity<NotificationPlanItem>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<NotificationPlanItem>>(ex);
			}
		}

		public GetUpdateCountResponse GetNotificationPlanItemUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<NotificationPlanItem>("NotificationPlanItem", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<NotificationPlanItem> GetNotificationPlanItemListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<NotificationPlanItem>("NotificationPlanItem", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<NotificationPlanItem>>(ex);
			}
		}

		public GetListResponse<NotificationPlanItem> GetNotificationPlanItemList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<NotificationPlanItem>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<NotificationPlanItem>>(ex);
			}
		}
		
		public BusinessMessageResponse SaveNotificationPlanItem(SaveRequest<NotificationPlanItem> request)
		{
			try
			{
				NotificationPlanItem entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				 			   
				object [] properties=new object[]
				{
						entity.ID,
						entity.Active,
						entity.Deleted,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.CompanyID,
						entity.UserID,
						entity.NotificationPlanID,
						entity.NotificationItemID,
						entity.CRMID,
						entity.DeliveryMethod

#if EntityProperty_NoDate
					,entity.`field`
#endif
#if EntityProperty_Date
					,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
				};
                var response = GenericSaveEntity<NotificationPlanItem>(entity.CompanyID, entity.Attributes, properties);  //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveNotificationPlanItemList(SaveListRequest<NotificationPlanItem> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (NotificationPlanItem entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object [] properties=new object[]
					{
						entity.ID,
						entity.Active,
						entity.Deleted,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.CompanyID,
						entity.UserID,
						entity.NotificationPlanID,
						entity.NotificationItemID,
						entity.CRMID,
						entity.DeliveryMethod
#if EntityProperty_NoDate
					,entity.`field`
#endif
#if EntityProperty_Date
					,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                    response = GenericSaveEntity<NotificationPlanItem>(entity.CompanyID, entity.Attributes, properties); 				     //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteNotificationPlanItem(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<NotificationPlanItem>("NotificationPlanItem", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}


