/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Runtime.Serialization;
using FernBusinessBase;
using FernBusinessBase.Control;

namespace ImardaNotificationBusiness
{
	[DataContract]
	public class Notification : FullBusinessEntity
	{
		#region Constructor
		public Notification()
		{
		}
		#endregion

		#region Properties

		[DataMember]
		public Guid NotificationPlanID { get; set; }

		public const int DescriptionMaxLen = 200;
		[ValidLength(0, DescriptionMaxLen)]
		[DataMember]
		public string Description { get; set; }

		public const int StatusMaxLen = 20;
		[ValidLength(-1, StatusMaxLen)]
		[DataMember]
		public string Status { get; set; }
#if EntityProperty
		[DataMember]
		public `cstype` `field` { get; set; }
#endif
		

		#endregion

		#region Methods
		public override void AssignData(IDataReader dr) 
		{
			base.AssignData(dr);
			NotificationPlanID = GetValue<Guid>(dr, "NotificationPlanID");
			Description = GetValue<string>(dr, "Description");
			Status = GetValue<string>(dr, "Status");
#if EntityProperty_NoDate
			`field` = GetColumn<`cstype`>(dr, "`field`");
#endif
#if EntityProperty_Date
			`field` = GetDateTime(dr, "`field`");
#endif
		

		}

		#endregion


	}
}
