/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaCRMBusiness 
{
	partial interface IImardaCRM 
	{

		#region Operation Contracts for EmailGroup
		[OperationContract]
		GetListResponse<EmailGroup> GetEmailGroupListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<EmailGroup> GetEmailGroupList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveEmailGroupList(SaveListRequest<EmailGroup> request);

		[OperationContract]
		BusinessMessageResponse SaveEmailGroup(SaveRequest<EmailGroup> request);

		[OperationContract]
		BusinessMessageResponse DeleteEmailGroup(IDRequest request);

		[OperationContract]
		GetItemResponse<EmailGroup> GetEmailGroup(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetEmailGroupUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


