/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 2:48 p.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaReportBusiness 
{
	partial interface IImardaReport 
	{

		#region Extra Operation Contracts for ReportType
		[OperationContract]
		BusinessMessageResponse ChangeReportTypeListOwner(SaveListRequest<ReportType> request);
		#endregion

	}
}


