/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaCRMBusiness 
{
	partial interface IImardaCRM 
	{

		#region Operation Contracts for Person
		[OperationContract]
		GetListResponse<Person> GetPersonListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<Person> GetPersonList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SavePersonList(SaveListRequest<Person> request);

		[OperationContract]
		BusinessMessageResponse SavePerson(SaveRequest<Person> request);

		[OperationContract]
		BusinessMessageResponse DeletePerson(IDRequest request);

		[OperationContract]
		GetItemResponse<Person> GetPerson(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetPersonUpdateCount(GetUpdateCountRequest request);

		#endregion

	}
}


