/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaTaskBusiness 
{
	partial interface IImardaTask 
	{

		#region Operation Contracts for Recurrence
		[OperationContract]
		GetListResponse<Recurrence> GetRecurrenceListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<Recurrence> GetRecurrenceList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveRecurrenceList(SaveListRequest<Recurrence> request);

		[OperationContract]
		BusinessMessageResponse SaveRecurrence(SaveRequest<Recurrence> request);

		[OperationContract]
		BusinessMessageResponse DeleteRecurrence(IDRequest request);

		[OperationContract]
		GetItemResponse<Recurrence> GetRecurrence(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetRecurrenceUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


