/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.Serialization;
using FernBusinessBase;
using System.Data;
using FernBusinessBase.Control;

namespace ImardaCRMBusiness 
{
	[DataContract]
	public class RoleType : FullBusinessEntity 
	{				
		#region Constructor
		public RoleType():base()
		{
		}
		#endregion
		
		#region Properties
		public const int NameMaxLen = 50;
		[ValidLength(0, NameMaxLen)]
		[DataMember]
		public string Name 
		{get ;set ;}
		public const int DescriptionMaxLen = 200;
		[ValidLength(0, DescriptionMaxLen)]
		[DataMember]
		public string Description 
		{get ;set ;}
#if EntityProperty
		[DataMember]
		public `cstype` `field` { get; set; }
#endif
		
		#endregion

		#region Methods
		public override void AssignData(IDataReader dr) 
		{
			base.AssignData(dr);
			Name = GetValue<string>(dr, "Name");
			Description = GetValue<string>(dr, "Description");
#if EntityProperty_NoDate
			`field` = GetValue<`cstype`>(dr, "`field`");
#endif
#if EntityProperty_Date
			`field` = GetDateTime(dr, "`field`");
#endif
		

		}

		#endregion

	
	}
}

