/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;
using Imarda.Lib;

namespace ImardaTaskBusiness
{
	[ServiceBehavior(InstanceContextMode = InstanceContextMode.Single, ConcurrencyMode = ConcurrencyMode.Multiple)]
	public partial class ImardaTask : FernBusinessBase.BusinessBase, IImardaTask 
	{

		public static readonly Guid InstanceID = SequentialGuid.NewDbGuid();
		public const string Description = "Task Infrastructure";

	}
}

