/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 12/05/2009 12:13 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System.ServiceModel;
using ImardaConfigurationBusiness;
using FernBusinessBase;

public class ImardaProxyManager
{
	#region ImardaProxyManager is a Singleton

		public static ImardaProxyManager Instance
		{
			get 
			{
				if (_Instance == null) _Instance = new ImardaProxyManager();
				return _Instance;
			}
		}

		private static ImardaProxyManager _Instance;

		/// <summary>
		/// Constructs the one and only ImardaProxyManager.
		/// </summary>
		private ImardaProxyManager()
		{

		}
	
		#endregion
	#region ImardaConfigurationService
	private Proxy<IImardaConfiguration> _IImardaConfigurationProxy
			= new Proxy<IImardaConfiguration>("ConfigurationTcpEndpoint");
		public IImardaConfiguration IImardaConfigurationProxy
		{
			get { return _IImardaConfigurationProxy.GetChannel(); }
		}

	#endregion
}



