/***********************************************************************
Auto Generated Code.

Generated by   : INZ09PC016\maurice.verheijen
Date Generated : 10-2-11 11:52 a.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Runtime.Serialization;
using FernBusinessBase;
using FernBusinessBase.Control;

namespace ImardaCRMBusiness 
{
	[DataContract]
	public class NotificationPlanItem : FullBusinessEntity 
	{				
		#region Constructor
		public NotificationPlanItem()
		{
		}
		#endregion
		
		#region Properties
		[DataMember]
		public Guid NotificationPlanID { get; set; }

		[DataMember]
		public Guid NotificationItemID { get; set; }

		[DataMember]
		public Guid CRMID { get; set; }

		public const int DeliveryMethodMaxLen = 50;
		[ValidLength(0, DeliveryMethodMaxLen)]
		[DataMember]
		public string DeliveryMethod { get; set; }

		#endregion

		#region Methods
#if EntityProperty
		[DataMember]
		public `cstype` `field` { get; set; }
#endif

		public override void AssignData(IDataReader dr) 
		{
			base.AssignData(dr);
			NotificationPlanID = GetValue<Guid>(dr, "NotificationPlanID");
			NotificationItemID = GetValue<Guid>(dr, "NotificationItemID");
			CRMID = GetValue<Guid>(dr, "CRMID");
			DeliveryMethod = GetValue<string>(dr, "DeliveryMethod");

#if EntityProperty_NoDate
			`field` = GetValue<`cstype`>(dr, "`field`");
#endif
#if EntityProperty_Date
			`field` = GetDateTime(dr, "`field`");
#endif
		}

		#endregion

	
	}
}

