/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;
namespace ImardaTaskBusiness
{
	partial class ImardaTask
	{

		#region Get TaskParameter
		public GetItemResponse<TaskParameter> GetTaskParameter(IDRequest request)
		{
			try
			{
				return GenericGetEntity<TaskParameter>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<TaskParameter>>(ex);
			}
		}
		#endregion
		#region GetTaskParameterUpdateCount
		

		public GetUpdateCountResponse GetTaskParameterUpdateCount(GetUpdateCountRequest request)
		{
			GetUpdateCountResponse response = new GetUpdateCountResponse();

			try
			{
				response = GenericGetEntityUpdateCount<TaskParameter>("TaskParameter", request.TimeStamp, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}

			return response;
		}
		#endregion
		#region GetTaskParameterListByTimeStamp
		

		public GetListResponse<TaskParameter> GetTaskParameterListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<TaskParameter>("TaskParameter", request.TimeStamp, request.Cap, true, request.IncludeInactive, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<TaskParameter>>(ex);
			}
		}
		#endregion
		#region GetTaskParameterList
		

		public GetListResponse<TaskParameter> GetTaskParameterList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<TaskParameter>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<TaskParameter>>(ex);
			}
		}
		#endregion
		#region Save TaskParameter
		public BusinessMessageResponse SaveTaskParameter(SaveRequest<TaskParameter> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				TaskParameter entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				 			   
				object [] properties=new object[]{			entity.ID,
						entity.TaskID,
						entity.Output,
						entity.Fixed,
						entity.Ord,
						entity.Name,
						entity.DataType,
						entity.DisplayName,
						entity.Value,
						entity.CompanyID,
						entity.UserID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Deleted,
						entity.Active
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
				response = GenericSaveEntity<TaskParameter>(entity.Attributes, properties);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region SaveTaskParameterList
		

		public BusinessMessageResponse SaveTaskParameterList(SaveListRequest<TaskParameter> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (TaskParameter entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object [] properties=new object[]
					{
						entity.ID,
						entity.TaskID,
						entity.Output,
						entity.Fixed,
						entity.Ord,
						entity.Name,
						entity.DataType,
						entity.DisplayName,
						entity.Value,
						entity.CompanyID,
						entity.UserID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Deleted,
						entity.Active
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
					response = GenericSaveEntity<TaskParameter>(entity.Attributes, properties); 				   
				}
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region Delete TaskParameter
		

		public BusinessMessageResponse DeleteTaskParameter(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<TaskParameter>("TaskParameter", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
		#endregion
	}
}


