/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 2:48 p.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using ImardaReportBusiness;

namespace TestBusinessHost.Services
{
	public class ImardaReportBusinessHost :ServiceHostBase
	{
		protected override Type ServiceType
		{
			get { return typeof(ImardaReportBusiness.ImardaReport ); }
		}

		protected override string ServiceName
		{
			get { return "Imarda Reporting Business Host"; }
		}
	}
}


