/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;
using System.Data;

namespace ImardaNotificationBusiness
{
	partial class ImardaNotification
	{
		public GetItemResponse<SMSPending> GetSMSPending(IDRequest request)
		{
			try
			{
				return GenericGetEntity<SMSPending>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<SMSPending>>(ex);
			}
		}

		public GetUpdateCountResponse GetSMSPendingUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<SMSPending>("SMSPending", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<SMSPending> GetSMSPendingListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<SMSPending>("SMSPending", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<SMSPending>>(ex);
			}
		}

		public GetListResponse<SMSPending> GetSMSPendingList(IDRequest request)
		{
			var result = new GetListResponse<SMSPending>();

			try
			{
				var db = ImardaDatabase.CreateDatabase(Util.GetConnName<SMSPending>());
				int numRecords = 100; //process 100 SMS at a time
				if (request.ContainsKey("NumRecords"))  //! IM-2342
					int.TryParse(request["NumRecords"], out numRecords);
				object[] args = new object[] { numRecords };
				using (IDataReader dr = db.ExecuteDataReader("SPGetSMSPendingList", args))
				{
					while (dr.Read())
					{
						result.List.Add(GetFromData<SMSPending>(dr));
					}

					return result;
				}

			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<SMSPending>>(ex);
			}
		}

		public BusinessMessageResponse SaveSMSPending(SaveRequest<SMSPending> request)
		{
			try
			{
				SMSPending entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				
				object[] properties = new object[]
				{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.SMSDraftID,
						entity.Subject,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToPhoneNumber,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
				var response = GenericSaveEntity<SMSPending>(entity.CompanyID, entity.Attributes, properties);   //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveSMSPendingList(SaveListRequest<SMSPending> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (SMSPending entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object[] properties = new object[]
					{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.SMSDraftID,
						entity.Subject,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToPhoneNumber,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
					response = GenericSaveEntity<SMSPending>(entity.CompanyID, entity.Attributes, properties);   //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteSMSPending(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<SMSPending>("SMSPending", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}

