/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using ImardaTaskBusiness;

namespace TestBusinessHost.Services
{
	public class ImardaTaskBusinessHost :ServiceHostBase
	{
		protected override Type ServiceType
		{
			get { return typeof(ImardaTaskBusiness.ImardaTask ); }
		}

		protected override string ServiceName
		{
			get { return "Imarda Task Business Host"; }
		}
	}
}


