/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;


namespace ImardaNotificationBusiness
{
	partial class ImardaNotification
	{
		public GetItemResponse<SMSFailed> GetSMSFailed(IDRequest request)
		{
			try
			{
				return GenericGetEntity<SMSFailed>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<SMSFailed>>(ex);
			}
		}

		public GetUpdateCountResponse GetSMSFailedUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<SMSFailed>("SMSFailed", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<SMSFailed> GetSMSFailedListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<SMSFailed>("SMSFailed", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<SMSFailed>>(ex);
			}
		}

		public GetListResponse<SMSFailed> GetSMSFailedList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<SMSFailed>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<SMSFailed>>(ex);
			}
		}

		public BusinessMessageResponse SaveSMSFailed(SaveRequest<SMSFailed> request)
		{
			try
			{
				SMSFailed entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				
				object[] properties = new object[]
				{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.SMSDraftID,
						entity.Subject,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToPhoneNumber,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
				var response = GenericSaveEntity<SMSFailed>(entity.CompanyID, entity.Attributes, properties);   //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveSMSFailedList(SaveListRequest<SMSFailed> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (SMSFailed entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object[] properties = new object[]
					{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.SMSDraftID,
						entity.Subject,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToPhoneNumber,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
					response = GenericSaveEntity<SMSFailed>(entity.CompanyID, entity.Attributes, properties);   //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteSMSFailed(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<SMSFailed>("SMSFailed", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}

