/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\qian.chen
Date Generated : 07/02/2011 11:32 a.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;


namespace ImardaSecurityBusiness
{
	partial class ImardaSecurity
	{
		public GetItemResponse<LogonLog> GetLogonLog(IDRequest request)
		{
			try
			{
				return GenericGetEntity<LogonLog>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<LogonLog>>(ex);
			}
		}

		public GetUpdateCountResponse GetLogonLogUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<LogonLog>("LogonLog", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<LogonLog> GetLogonLogListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<LogonLog>("LogonLog", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<LogonLog>>(ex);
			}
		}

		public GetListResponse<LogonLog> GetLogonLogList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<LogonLog>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<LogonLog>>(ex);
			}
		}
		
		public BusinessMessageResponse SaveLogonLog(SaveRequest<LogonLog> request)
		{
			try
			{
				LogonLog entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				 			   
				object [] properties=new object[]
				{
						entity.ID,
						entity.SecurityEntityID,
						entity.Success,
						entity.CompanyID,
						entity.UserID,
						entity.Active,
						entity.Deleted,
                  entity.DateModified = DateTime.UtcNow,
                  entity.DateCreated,
						entity.HostIPAddress,
						entity.ApplicationID,
						entity.SessionObjectID,
						entity.Logon,
						entity.FailureCode
					,entity.LoginUsername
#if EntityProperty_NoDate
					,entity.`field`
#endif
#if EntityProperty_Date
					,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
				};
                var response = GenericSaveEntity<LogonLog>(entity.CompanyID, entity.Attributes, properties);  //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveLogonLogList(SaveListRequest<LogonLog> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (LogonLog entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object [] properties=new object[]
					{
						entity.ID,
						entity.SecurityEntityID,
						entity.Success,
						entity.CompanyID,
						entity.UserID,
						entity.Active,
						entity.Deleted,
                  entity.DateModified = DateTime.UtcNow,
                  entity.DateCreated,
						entity.HostIPAddress,
						entity.ApplicationID,
						entity.SessionObjectID,
						entity.Logon,
						entity.FailureCode
					,entity.LoginUsername
#if EntityProperty_NoDate
					,entity.`field`
#endif
#if EntityProperty_Date
					,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                    response = GenericSaveEntity<LogonLog>(entity.CompanyID, entity.Attributes, properties); 				     //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteLogonLog(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<LogonLog>("LogonLog", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}


