/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 2:48 p.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaReportBusiness 
{
	partial interface IImardaReport 
	{

		#region Operation Contracts for Report
		[OperationContract]
		GetListResponse<Report> GetReportListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<Report> GetReportList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveReportList(SaveListRequest<Report> request);

		[OperationContract]
		BusinessMessageResponse SaveReport(SaveRequest<Report> request);

		[OperationContract]
		BusinessMessageResponse DeleteReport(IDRequest request);

		[OperationContract]
		GetItemResponse<Report> GetReport(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetReportUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


