/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;


namespace ImardaNotificationBusiness
{
	partial class ImardaNotification
	{
		public GetItemResponse<EmailDraft> GetEmailDraft(IDRequest request)
		{
			try
			{
				return GenericGetEntity<EmailDraft>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<EmailDraft>>(ex);
			}
		}

		public GetUpdateCountResponse GetEmailDraftUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<EmailDraft>("EmailDraft", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<EmailDraft> GetEmailDraftListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<EmailDraft>("EmailDraft", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<EmailDraft>>(ex);
			}
		}

		public GetListResponse<EmailDraft> GetEmailDraftList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<EmailDraft>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<EmailDraft>>(ex);
			}
		}

		public BusinessMessageResponse SaveEmailDraft(SaveRequest<EmailDraft> request)
		{
			try
			{
				EmailDraft entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				
				object[] properties = new object[]
				{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.Subject,
						entity.FromAddress,
						entity.Message,
						entity.NotificationID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Active,
						entity.Deleted
						,entity.Priority
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                var response = GenericSaveEntity<EmailDraft>(entity.CompanyID, entity.Attributes, properties);    //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveEmailDraftList(SaveListRequest<EmailDraft> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (EmailDraft entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object[] properties = new object[]
					{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.Subject,
						entity.FromAddress,
						entity.Message,
						entity.NotificationID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Active,
						entity.Deleted
						,entity.Priority
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                    response = GenericSaveEntity<EmailDraft>(entity.CompanyID, entity.Attributes, properties);    //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteEmailDraft(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<EmailDraft>("EmailDraft", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}

