/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:08 PM
Copyright @2009 CodeGenerator
***********************************************************************/

#region

using System.ServiceModel;
using FernBusinessBase;

#endregion

// ReSharper disable once CheckNamespace
namespace Cormit.Business.RouteTracking 
{
	[ServiceContract]
	public partial interface ICormitRouteTracking : IServerFacadeBase 
	{
	}
}

