/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.ServiceModel;
using System.Xml;
using System.ServiceModel.Channels;
//using System.Web.Services.Description;
using ImardaCRMBusiness ;
using FernBusinessBase;

public public class ImardaProxyManager
{
	#region ImardaCRMService
	private Proxy<IImardaCRM> _IImardaCRMProxy
			= new Proxy<IImardaCRM>("CRMTcpEndpoint");
		public IImardaCRM IImardaCRMProxy
		{
			get { return _IImardaCRMProxy.GetChannel(); }
		}

	#endregion
}



