/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;


namespace ImardaNotificationBusiness
{
	partial class ImardaNotification
	{
		public GetItemResponse<EmailFailed> GetEmailFailed(IDRequest request)
		{
			try
			{
				return GenericGetEntity<EmailFailed>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<EmailFailed>>(ex);
			}
		}

		public GetUpdateCountResponse GetEmailFailedUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<EmailFailed>("EmailFailed", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<EmailFailed> GetEmailFailedListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<EmailFailed>("EmailFailed", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<EmailFailed>>(ex);
			}
		}

		public GetListResponse<EmailFailed> GetEmailFailedList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<EmailFailed>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<EmailFailed>>(ex);
			}
		}

		public BusinessMessageResponse SaveEmailFailed(SaveRequest<EmailFailed> request)
		{
			try
			{
				EmailFailed entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				
				object[] properties = new object[]
				{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.EmailDraftID,
						entity.Subject,
						entity.FromAddress,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToAddress,
						entity.CC,
						entity.Bcc,
						entity.AttachmentFiles,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
						,entity.Priority
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                var response = GenericSaveEntity<EmailFailed>(entity.CompanyID, entity.Attributes, properties);    //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveEmailFailedList(SaveListRequest<EmailFailed> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (EmailFailed entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object[] properties = new object[]
					{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.EmailDraftID,
						entity.Subject,
						entity.FromAddress,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToAddress,
						entity.CC,
						entity.Bcc,
						entity.AttachmentFiles,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
						,entity.Priority
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                    response = GenericSaveEntity<EmailFailed>(entity.CompanyID, entity.Attributes, properties);    //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteEmailFailed(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<EmailFailed>("EmailFailed", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}

