/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 12/05/2009 12:13 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using ImardaConfigurationBusiness;
using Imarda.Lib;

namespace ImardaConfiguration
{

	public class ImardaConfigurationService : FernServiceBase.FernServiceBase
	{

		/// <summary>
		/// Passes the specific args for this Service to the base class
		/// </summary>
		public ImardaConfigurationService()
			: base("ImardaConfiguration")
		{
			RegisterHost(new ImardaServiceHost(typeof(ImardaConfigurationBusiness.ImardaConfiguration)));
		}

		/// <summary>
		/// Main program entry point
		/// </summary>
		public static void Main()
		{
			System.ServiceProcess.ServiceBase[] ServicesToRun;
			ServicesToRun = new System.ServiceProcess.ServiceBase[] { new ImardaConfigurationService() };
			System.ServiceProcess.ServiceBase.Run(ServicesToRun);
		}

		#region Methods to re-initialize, or update, the database.
		/*protected override void internalUpdateDatabase(SqlConnection conn) 
		{
			
		}*/
		#endregion
	}
}

