/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 12/05/2009 12:13 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernServiceBase;

namespace ImardaConfigurationService {
	public class ProjectInstaller : BaseProjectInstaller {
		public ProjectInstaller()
			: base("ImardaConfiguration", "ImardaConfigurationService",
			"Provides Advanced Configuration Support for Key Functionality") { }
	}
}


