/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/03/2010 12:10 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Runtime.Serialization;
using FernBusinessBase;
using FernBusinessBase.Control;

namespace ImardaCRMBusiness 
{
	[DataContract]
	public class NotificationHistory : FullBusinessEntity 
	{				
		#region Constructor
		public NotificationHistory()
		{
		}
		#endregion
		
		#region Properties

		[DataMember]
		public Guid CRMID { get; set; }

		[DataMember]
		public Guid NotificationPlanID { get; set; }

		public const int DeliveryMethodMaxLen = 50;
		[ValidLength(0, DeliveryMethodMaxLen)]
		[DataMember]
		public string DeliveryMethod { get; set; }

		[DataMember]
		public string Content { get; set; }

		public const int StatusMaxLen = 50;
		[ValidLength(0, StatusMaxLen)]
		[DataMember]
		public string Status { get; set; }
#if EntityProperty
		[DataMember]
		public `cstype` `field` { get; set; }
#endif
		

		#endregion

		#region Methods
		public override void AssignData(IDataReader dr) 
		{
			base.AssignData(dr);
			CRMID = GetValue<Guid>(dr, "CRMID");
			NotificationPlanID = GetValue<Guid>(dr, "NotificationPlanID");
			DeliveryMethod = GetValue<string>(dr, "DeliveryMethod");
			Content = GetValue<string>(dr, "Content");
			Status = GetValue<string>(dr, "Status");
#if EntityProperty_NoDate
			`field` = GetValue<`cstype`>(dr, "`field`");
#endif
#if EntityProperty_Date
			`field` = GetDateTime(dr, "`field`");
#endif
		
		}

		#endregion

	
	}
}

