/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for Notification
		[OperationContract]
		GetListResponse<Notification> GetNotificationListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<Notification> GetNotificationList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveNotificationList(SaveListRequest<Notification> request);

		[OperationContract]
		BusinessMessageResponse SaveNotification(SaveRequest<Notification> request);

		[OperationContract]
		BusinessMessageResponse DeleteNotification(IDRequest request);

		[OperationContract]
		GetItemResponse<Notification> GetNotification(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetNotificationUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


