/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaCRMBusiness 
{
	partial interface IImardaCRM 
	{

		#region Operation Contracts for Role
		[OperationContract]
		GetListResponse<Role> GetRoleListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<Role> GetRoleList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveRoleList(SaveListRequest<Role> request);

		[OperationContract]
		BusinessMessageResponse SaveRole(SaveRequest<Role> request);

		[OperationContract]
		BusinessMessageResponse DeleteRole(IDRequest request);

		[OperationContract]
		GetItemResponse<Role> GetRole(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetRoleUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


