/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;
namespace ImardaTaskBusiness
{
	partial class ImardaTask
	{

		#region Get Task
		public GetItemResponse<Task> GetTask(IDRequest request)
		{
			try
			{
				return GenericGetEntity<Task>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<Task>>(ex);
			}
		}
		#endregion
		#region GetTaskUpdateCount
		

		public GetUpdateCountResponse GetTaskUpdateCount(GetUpdateCountRequest request)
		{
			GetUpdateCountResponse response = new GetUpdateCountResponse();

			try
			{
				response = GenericGetEntityUpdateCount<Task>("Task", request.TimeStamp, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}

			return response;
		}
		#endregion
		#region GetTaskListByTimeStamp
		

		public GetListResponse<Task> GetTaskListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<Task>("Task", request.TimeStamp, request.Cap, true, request.IncludeInactive, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<Task>>(ex);
			}
		}
		#endregion
		#region GetTaskList
		

		public GetListResponse<Task> GetTaskList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<Task>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<Task>>(ex);
			}
		}
		#endregion
		#region Save Task
		public BusinessMessageResponse SaveTask(SaveRequest<Task> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				Task entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				 			   
				object [] properties=new object[]{			entity.ID,
						entity.ParentID,
						entity.Ord,
						entity.IsTemplate,
						entity.Precondition,
						entity.Program,
						entity.Worker,
						entity.Status,
						entity.EstimatedDuration,
						entity.EndTime,
						entity.CompanyID,
						entity.UserID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Deleted,
						entity.Active
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
				response = GenericSaveEntity<Task>(entity.Attributes, properties);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region SaveTaskList
		

		public BusinessMessageResponse SaveTaskList(SaveListRequest<Task> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (Task entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object [] properties=new object[]
					{
						entity.ID,
						entity.ParentID,
						entity.Ord,
						entity.IsTemplate,
						entity.Precondition,
						entity.Program,
						entity.Worker,
						entity.Status,
						entity.EstimatedDuration,
						entity.EndTime,
						entity.CompanyID,
						entity.UserID,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.Deleted,
						entity.Active
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
					response = GenericSaveEntity<Task>(entity.Attributes, properties); 				   
				}
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region Delete Task
		

		public BusinessMessageResponse DeleteTask(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<Task>("Task", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
		#endregion
	}
}


