/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for EmailPending
		[OperationContract]
		GetListResponse<EmailPending> GetEmailPendingListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<EmailPending> GetEmailPendingList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveEmailPendingList(SaveListRequest<EmailPending> request);

		[OperationContract]
		BusinessMessageResponse SaveEmailPending(SaveRequest<EmailPending> request);

		[OperationContract]
		BusinessMessageResponse DeleteEmailPending(IDRequest request);

		[OperationContract]
		GetItemResponse<EmailPending> GetEmailPending(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetEmailPendingUpdateCount(GetUpdateCountRequest request);
		#endregion

	}
}


