/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Data;
using System.Configuration;
using System.ServiceModel;
using System.Xml;
using System.ServiceModel.Channels;
//using System.Web.Services.Description;
using ImardaTaskBusiness ;
using FernBusinessBase;

public public class ImardaProxyManager
{
	#region ImardaTaskService
	private Proxy<IImardaTask> _IImardaTaskProxy
			= new Proxy<IImardaTask>("TaskTcpEndpoint");
		public IImardaTask IImardaTaskProxy
		{
			get { return _IImardaTaskProxy.GetChannel(); }
		}

	#endregion
}



