/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\maurice.verheijen
Date Generated : 24/06/2009 9:55 a.m.
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;
using FernBusinessBase;
using ImardaTaskBusiness; 
namespace ImardaTestClient
{
	
	[TestFixture]  
	public partial class TestClient
	{
		Guid _CompanyID = Guid.NewGuid();
		[SetUp]
		public void Init()
		{
				
		}
		private void initFullEntity(FullBusinessEntity entity,Guid id)
		{
			entity.ID = id;
			entity.UserID = Guid.NewGuid();
			entity.Active = true;
			entity.DateCreated = DateTime.Now;
			entity.DateModified = DateTime.Now;
			entity.CompanyID = _CompanyID ;
			entity.Deleted = false;
		} 	   

		[Test] 
		public void RecurrenceSelect()
		{
			GetItemResponse<ImardaTaskBusiness.Recurrence> busResponse = null;

			IImardaTask channel = ImardaProxyManager.Instance.IImardaTaskProxy ;
			var service = ImardaProxyManager.Instance.${Proxy};
				ChannelInvoker.Invoke(delegate(out IClientChannel channel)
				{
					channel = service as IC				
				IDRequest request = new IDRequest();
				request.ID = Guid.NewGuid();
				busResponse = channel.GetRecurrence (request);
			}
			if (busResponse != null && busResponse.Status && busResponse.Item != null)
			{ 			   
			}
		}
		[Test] 
		public void ScheduledTaskSelect()
		{
			GetItemResponse<ImardaTaskBusiness.ScheduledTask> busResponse = null;

			IImardaTask channel = ImardaProxyManager.Instance.IImardaTaskProxy ;
			var service = ImardaProxyManager.Instance.${Proxy};
				ChannelInvoker.Invoke(delegate(out IClientChannel channel)
				{
					channel = service as IC				
				IDRequest request = new IDRequest();
				request.ID = Guid.NewGuid();
				busResponse = channel.GetScheduledTask (request);
			}
			if (busResponse != null && busResponse.Status && busResponse.Item != null)
			{ 			   
			}
		}
		[Test] 
		public void TaskSelect()
		{
			GetItemResponse<ImardaTaskBusiness.Task> busResponse = null;

			IImardaTask channel = ImardaProxyManager.Instance.IImardaTaskProxy ;
			var service = ImardaProxyManager.Instance.${Proxy};
				ChannelInvoker.Invoke(delegate(out IClientChannel channel)
				{
					channel = service as IC				
				IDRequest request = new IDRequest();
				request.ID = Guid.NewGuid();
				busResponse = channel.GetTask (request);
			}
			if (busResponse != null && busResponse.Status && busResponse.Item != null)
			{ 			   
			}
		}
		[Test] 
		public void TaskParameterSelect()
		{
			GetItemResponse<ImardaTaskBusiness.TaskParameter> busResponse = null;

			IImardaTask channel = ImardaProxyManager.Instance.IImardaTaskProxy ;
			var service = ImardaProxyManager.Instance.${Proxy};
				ChannelInvoker.Invoke(delegate(out IClientChannel channel)
				{
					channel = service as IC				
				IDRequest request = new IDRequest();
				request.ID = Guid.NewGuid();
				busResponse = channel.GetTaskParameter (request);
			}
			if (busResponse != null && busResponse.Status && busResponse.Item != null)
			{ 			   
			}
		}

		
	}
}


