/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using System.ServiceModel;
using FernBusinessBase;

namespace ImardaNotificationBusiness 
{
	partial interface IImardaNotification 
	{

		#region Operation Contracts for EmailFailed
		[OperationContract]
		GetListResponse<EmailFailed> GetEmailFailedListByTimeStamp(GetListByTimestampRequest request);

		[OperationContract]
		GetListResponse<EmailFailed> GetEmailFailedList(IDRequest request);

		[OperationContract]
		BusinessMessageResponse SaveEmailFailedList(SaveListRequest<EmailFailed> request);

		[OperationContract]
		BusinessMessageResponse SaveEmailFailed(SaveRequest<EmailFailed> request);

		[OperationContract]
		BusinessMessageResponse DeleteEmailFailed(IDRequest request);

		[OperationContract]
		GetItemResponse<EmailFailed> GetEmailFailed(IDRequest request);

		[OperationContract]
		GetUpdateCountResponse GetEmailFailedUpdateCount(GetUpdateCountRequest request);
		
		[OperationContract]
		GetListResponse<EmailFailed> GetEmailFailedDueList(IDRequest request);
		#endregion

	}
}


