/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:08 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernServiceBase;

namespace ImardaTrackingService {
	public class ProjectInstaller : BaseProjectInstaller {
		public ProjectInstaller()
			: base("CormitRouteTracking", "ImardaTrackingService",
			"Provides and Manages Generic Location Tracking Information "){ }
	}
}


