/***********************************************************************
Auto Generated Code

Generated by   : PROLIFICXNZ\adamson.delacruz
Date Generated : 27/04/2009 1:27 PM
Copyright @2009 CodeGenerator
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;
namespace ImardaCRMBusiness
{
	partial class ImardaCRM
	{

		#region Get CompanyModule
		public GetItemResponse<CompanyModule> GetCompanyModule(IDRequest request)
		{
			try
			{
				return GenericGetEntity<CompanyModule>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<CompanyModule>>(ex);
			}
		}
		#endregion
		#region GetCompanyModuleUpdateCount
		

		public GetUpdateCountResponse GetCompanyModuleUpdateCount(GetUpdateCountRequest request)
		{
			GetUpdateCountResponse response = new GetUpdateCountResponse();

			try
			{
				response = GenericGetEntityUpdateCount<CompanyModule>("CompanyModule", request.TimeStamp, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}

			return response;
		}
		#endregion
		#region GetCompanyModuleListByTimeStamp
		

		public GetListResponse<CompanyModule> GetCompanyModuleListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<CompanyModule>("CompanyModule", request.TimeStamp, request.Cap, true, request.IncludeInactive, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<CompanyModule>>(ex);
			}
		}
		#endregion
		#region GetCompanyModuleList
		

		public GetListResponse<CompanyModule> GetCompanyModuleList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<CompanyModule>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<CompanyModule>>(ex);
			}
		}
		#endregion
		#region Save CompanyModule
		public BusinessMessageResponse SaveCompanyModule(SaveRequest<CompanyModule> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				CompanyModule entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				 			   
				object [] properties=new object[]{			entity.ID,
						entity.Active,
						entity.Deleted,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.CompanyID,
						entity.UserID,
						entity.RoleName
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                response = GenericSaveEntity<CompanyModule>(entity.CompanyID, entity.Attributes, properties);    //Review IM-3747
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region SaveCompanyModuleList
		

		public BusinessMessageResponse SaveCompanyModuleList(SaveListRequest<CompanyModule> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (CompanyModule entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object [] properties=new object[]
					{
						entity.ID,
						entity.Active,
						entity.Deleted,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.CompanyID,
						entity.UserID,
						entity.RoleName
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
                    response = GenericSaveEntity<CompanyModule>(entity.CompanyID, entity.Attributes, properties); 				       //Review IM-3747
				}
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
			return response;
		}
		#endregion
		#region Delete CompanyModule
		

		public BusinessMessageResponse DeleteCompanyModule(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<CompanyModule>("CompanyModule", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
		#endregion
	}
}


