/***********************************************************************
Auto Generated Code.

Generated by   : IMARDAINC\Qian.Chen
Date Generated : 12/02/2010 3:40 p.m.
Copyright (c)2009 CodeGenerator 1.2
***********************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using FernBusinessBase;
using FernBusinessBase.Errors;


namespace ImardaNotificationBusiness
{
	partial class ImardaNotification
	{
		public GetItemResponse<SMSSent> GetSMSSent(IDRequest request)
		{
			try
			{
				return GenericGetEntity<SMSSent>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetItemResponse<SMSSent>>(ex);
			}
		}

		public GetUpdateCountResponse GetSMSSentUpdateCount(GetUpdateCountRequest request)
		{
			try
			{
				var response = GenericGetEntityUpdateCount<SMSSent>("SMSSent", request.TimeStamp, true, request.ID, request.LastRecordID);
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetUpdateCountResponse>(ex);
			}
		}

		public GetListResponse<SMSSent> GetSMSSentListByTimeStamp(GetListByTimestampRequest request)
		{
			try
			{
				return GenericGetEntityListByTimestamp<SMSSent>("SMSSent", request.TimeStamp, request.Cap, true, request.ID, request.LastRecordID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<SMSSent>>(ex);
			}
		}

		public GetListResponse<SMSSent> GetSMSSentList(IDRequest request)
		{
			try
			{
				return GenericGetEntityList<SMSSent>(request);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle<GetListResponse<SMSSent>>(ex);
			}
		}

		public BusinessMessageResponse SaveSMSSent(SaveRequest<SMSSent> request)
		{
			try
			{
				SMSSent entity = request.Item;
				BaseEntity.ValidateThrow(entity);
				
				object[] properties = new object[]
				{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.SMSDraftID,
						entity.Subject,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToPhoneNumber,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
				var response = GenericSaveEntity<SMSSent>(entity.CompanyID, entity.Attributes, properties);   //Review IM-3747
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse SaveSMSSentList(SaveListRequest<SMSSent> request)
		{
			var response = new BusinessMessageResponse();
			try
			{
				foreach (SMSSent entity in request.List)
				{
					BaseEntity.ValidateThrow(entity);
					object[] properties = new object[]
					{
						entity.ID,
						entity.CompanyID,
						entity.UserID,
						entity.SMSDraftID,
						entity.Subject,
						entity.Message,
						entity.NotificationID,
						entity.RecipientName,
						entity.ToPhoneNumber,
						entity.Retry,
						entity.TimeToSend,
						entity.Status,
						entity.DateCreated,
						entity.DateModified = DateTime.UtcNow,
						entity.LastRetryAt,
						entity.Active,
						entity.Deleted
#if EntityProperty_NoDate
						,entity.`field`
#endif
#if EntityProperty_Date
						,BusinessBase.ReadyDateForStorage(entity.`field`)
#endif
					};
					response = GenericSaveEntity<SMSSent>(entity.CompanyID, entity.Attributes, properties);   //Review IM-3747
				}
				return response;
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}

		public BusinessMessageResponse DeleteSMSSent(IDRequest request)
		{
			try
			{
				return GenericDeleteEntity<SMSSent>("SMSSent", request.ID);
			}
			catch (Exception ex)
			{
				return ErrorHandler.Handle(ex);
			}
		}
	}
}